[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile && cd artifacts/zing-crm && pnpm run build && cd ../../artifacts/api-server && node ./build.mjs"

[deploy]
startCommand = "node --enable-source-maps artifacts/api-server/dist/index.mjs"
